corner-radius = 5;

rounded-corners-exclude = [
  "class_g = 'Polybar'" # Stop doing crime by rounding the bar
];

shadow = false;

vsync = true;

use-damage = true;

backend = "glx";

fading = true
fade-in-step = 1
fade-out-step = 1
fade-delta = 50
